export enum DishActionTypesEnum {
  ADD_DISH = 'ADD_DISH',
  ADD_DISH_SUCCESS = 'ADD_DISH_SUCCESS',
  ADD_DISH_END = 'ADD_DISH_END',
  ADD_DISH_FAIL = 'ADD_DISH_FAIL',
  ADD_DISH_START = 'ADD_DISH_START',
  GET_DISHES = 'GET_DISHES',
  GET_DISHES_SUCCESS = 'GET_DISHES_SUCCESS',
  GET_DISHES_END = 'GET_DISHES_END',
  GET_DISHES_FAIL = 'GET_DISHES_FAIL',
  GET_DISHES_START = 'GET_DISHES_START',
}